# Use an official OpenJDK runtime as the base image
FROM openjdk:17
# Expose the application port (change if necessary)
EXPOSE 8761
# Add the JAR file to the Docker image
ADD target/springboot-images-new.jar springboot-images-new.jar
# Set the entry point for the application
ENTRYPOINT ["java", "-jar", "/springboot-images-new.jar"]
