FROM openjdk:17-jdk-slim

WORKDIR /app

# Make sure the path matches the Maven target output
COPY ./discovery/target/discovery-0.0.1.SNAPSHOT.jar /app/discovery-0.0.1.SNAPSHOT.jar

CMD ["java", "-jar", "/app/discovery-0.0.1.SNAPSHOT.jar"]
