

FROM openjdk:17-jdk-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier JAR construit par Maven dans le conteneur
COPY ./target/discovery-0.0.1.SNAPSHOT.jar /app/discovery-0.0.1.SNAPSHOT.jar


# Exposer le port que le microservice utilisera
EXPOSE 8761

# Définir la commande pour exécuter le fichier JAR
ENTRYPOINT  ["java", "-jar", "/app/discovery-0.0.1.SNAPSHOT.jar"]
