name: discovery CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./discovery/mvnw

      - name: Build with Maven
        working-directory: ./discovery
        run: ./mvnw -B package


        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set up DOCKER_USERNAME in GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set up DOCKER_PASSWORD in GitHub secrets

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/discovery:latest -f ./discovery/Dockerfile ./discovery

      - name: Push Docker image
        run: docker push your-dockerhub-username/discovery:latest 


        
